### ISSUE TITLE
r2pm -i valabind Sorry. This package cannot be installed at home

### ISSUE THREAD

**Issue by Maijin** [radare/radare2-pm#39]

**Comment by radare** [comment]
thats false

$ r2pm -i valabind
…
4 warnings generated.
Compilation succeeded - 3 warning(s)
mkdir -p /Users/pancake/.config/radare2/prefix/bin
mkdir -p /Users/pancake/.config/radare2/prefix/share/man/man1
install -m0644 valabind.1 /Users/pancake/.config/radare2/prefix/share/man/man1
install -m0644 valabind-cc.1 /Users/pancake/.config/radare2/prefix/share/man/man1
install -m0755 valabind /Users/pancake/.config/radare2/prefix/bin
install -m0755 valabind-cc /Users/pancake/.config/radare2/prefix/bin

**Comment by Maijin** [comment]
Let's wait for travis then.

**Comment by Maijin** [comment]
This has been fixed cool https://travis-ci.org/radare/radare2-extras/jobs/204700426
