### ISSUE TITLE
r2frida make cylang default to off?

### ISSUE THREAD

**Issue by dweinstein** [radare/radare2-pm#55]

**Comment by radare** [comment]
it is off by default already unless you set the R2FRIDA_CYLANG env var

**Comment by dweinstein** [comment]
doesn't seem to work that way, when I ran `r2pm -i r2frida` without any env var set it seemed to be building w/ cylang AFAICT, test for yourself?

**Comment by dweinstein** [comment]
I had to update my r2pm pkg it seems
